# Generated by Django 4.2.7 on 2023-12-04 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='firstname',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'You can insert only letters.')]),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='lastname',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'You can insert only letters.')]),
        ),
    ]
